// <auto-generated />
using System;
using MenuService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuService.API.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20260322210116_InitialMenuServiceMigration")]
    partial class InitialMenuServiceMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MenuService.API.Models.BundlePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("BundlePrices");
                });

            modelBuilder.Entity("MenuService.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantConfigId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 905, DateTimeKind.Utc).AddTicks(1730),
                            Description = "All types of pizzas",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Pizzas",
                            RestaurantConfigId = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 905, DateTimeKind.Utc).AddTicks(1740)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 905, DateTimeKind.Utc).AddTicks(2320),
                            Description = "Starters and appetizers",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Appetizers",
                            RestaurantConfigId = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 905, DateTimeKind.Utc).AddTicks(2320)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 905, DateTimeKind.Utc).AddTicks(2320),
                            Description = "Sweet treats",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Desserts",
                            RestaurantConfigId = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 905, DateTimeKind.Utc).AddTicks(2320)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 905, DateTimeKind.Utc).AddTicks(2320),
                            Description = "Drinks and beverages",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Beverages",
                            RestaurantConfigId = 1,
                            UpdatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 905, DateTimeKind.Utc).AddTicks(2320)
                        });
                });

            modelBuilder.Entity("MenuService.API.Models.ComboDeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ComboPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DealName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQuantityPerOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OriginalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantConfigId");

                    b.ToTable("ComboDeals");
                });

            modelBuilder.Entity("MenuService.API.Models.ComboDealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComboDealId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterchangeableGroup")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInterchangeable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComboDealId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("ComboDealItems");
                });

            modelBuilder.Entity("MenuService.API.Models.CustomizationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumSelections")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumSelections")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("CustomizationGroups");
                });

            modelBuilder.Entity("MenuService.API.Models.CustomizationOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdditionalCalories")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomizationGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomizationGroupId");

                    b.ToTable("CustomizationOptions");
                });

            modelBuilder.Entity("MenuService.API.Models.EnhancedMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllergenInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Carbohydrates")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultSpiceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Fat")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPopularItem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeasonalItem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreparationTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Protein")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecommendationScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestaurantConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SeasonalEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SeasonalStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubcategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportSpiceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantConfigId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("EnhancedMenuItems");
                });

            modelBuilder.Entity("MenuService.API.Models.ItemVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceModifier")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("ItemVariants");
                });

            modelBuilder.Entity("MenuService.API.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("MenuService.API.Models.RestaurantConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowSubcategories")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAllergenInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableBundlePricing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableComboDeals")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDynamicPricing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableNutritionalInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePreparationTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSeasonalItems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSpiceLevelCustomization")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCustomizationOptionsPerItem")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("OperatingHoursEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("OperatingHoursStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireItemVariants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("RestaurantConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowSubcategories = true,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 904, DateTimeKind.Utc).AddTicks(7570),
                            CuisineType = "Italian",
                            CurrencyCode = "USD",
                            Description = "Premium Italian Pizza Restaurant",
                            EnableAllergenInfo = true,
                            EnableBundlePricing = true,
                            EnableComboDeals = true,
                            EnableDynamicPricing = false,
                            EnableNutritionalInfo = true,
                            EnablePreparationTime = true,
                            EnableSeasonalItems = true,
                            EnableSpiceLevelCustomization = true,
                            IsActive = true,
                            MaxCustomizationOptionsPerItem = 5,
                            OperatingHoursEnd = new TimeSpan(0, 23, 0, 0, 0),
                            OperatingHoursStart = new TimeSpan(0, 11, 0, 0, 0),
                            RequireItemVariants = false,
                            RestaurantId = "pizza_place_001",
                            RestaurantName = "Pizza Palace",
                            RestaurantType = "Pizza",
                            UpdatedAt = new DateTime(2026, 3, 22, 21, 1, 15, 904, DateTimeKind.Utc).AddTicks(7570)
                        });
                });

            modelBuilder.Entity("MenuService.API.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("MenuService.API.Models.BundlePrice", b =>
                {
                    b.HasOne("MenuService.API.Models.EnhancedMenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("MenuService.API.Models.Category", b =>
                {
                    b.HasOne("MenuService.API.Models.RestaurantConfig", "RestaurantConfig")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantConfig");
                });

            modelBuilder.Entity("MenuService.API.Models.ComboDeal", b =>
                {
                    b.HasOne("MenuService.API.Models.RestaurantConfig", "RestaurantConfig")
                        .WithMany("ComboDeals")
                        .HasForeignKey("RestaurantConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantConfig");
                });

            modelBuilder.Entity("MenuService.API.Models.ComboDealItem", b =>
                {
                    b.HasOne("MenuService.API.Models.ComboDeal", "ComboDeal")
                        .WithMany("Items")
                        .HasForeignKey("ComboDealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuService.API.Models.EnhancedMenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComboDeal");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("MenuService.API.Models.CustomizationGroup", b =>
                {
                    b.HasOne("MenuService.API.Models.EnhancedMenuItem", "MenuItem")
                        .WithMany("CustomizationGroups")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("MenuService.API.Models.CustomizationOption", b =>
                {
                    b.HasOne("MenuService.API.Models.CustomizationGroup", "CustomizationGroup")
                        .WithMany("Options")
                        .HasForeignKey("CustomizationGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizationGroup");
                });

            modelBuilder.Entity("MenuService.API.Models.EnhancedMenuItem", b =>
                {
                    b.HasOne("MenuService.API.Models.Category", "Category")
                        .WithMany("EnhancedMenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MenuService.API.Models.RestaurantConfig", "RestaurantConfig")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuService.API.Models.Subcategory", "Subcategory")
                        .WithMany("MenuItems")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("RestaurantConfig");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("MenuService.API.Models.ItemVariant", b =>
                {
                    b.HasOne("MenuService.API.Models.EnhancedMenuItem", "MenuItem")
                        .WithMany("Variants")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("MenuService.API.Models.MenuItem", b =>
                {
                    b.HasOne("MenuService.API.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MenuService.API.Models.Subcategory", b =>
                {
                    b.HasOne("MenuService.API.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MenuService.API.Models.Category", b =>
                {
                    b.Navigation("EnhancedMenuItems");

                    b.Navigation("MenuItems");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("MenuService.API.Models.ComboDeal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MenuService.API.Models.CustomizationGroup", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MenuService.API.Models.EnhancedMenuItem", b =>
                {
                    b.Navigation("CustomizationGroups");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MenuService.API.Models.RestaurantConfig", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ComboDeals");

                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("MenuService.API.Models.Subcategory", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
